defaultContentLanguage: en
enableRobotsTXT: false
relativeURLs: true
uglyURLs: true
enableGitInfo: true
metaDataFormat: yaml

languages:
  en:
    title: Manual for OpenEstate-ImmoTool
    baseURL: https://manual.openestate.org/en/
    contentDir: content/en
    languageName: English
    weight: 10
    params:
      dateTimeFormat: "01/02/2006 at 03:04 PM (MST)"
      licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/deed"

  de:
    title: Handbuch für OpenEstate-ImmoTool
    baseURL: https://manual.openestate.org/de/
    contentDir: content/de
    languageName: Deutsch
    weight: 20
    params:
      dateTimeFormat: "02.01.2006 um 15:04 Uhr (MST)"
      licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/deed.de"

blackfriday:
  taskLists: false
  smartypants: false
  angledQuotes: true
  smartDashes: true

disableKinds:
- sitemap
- RSS
- taxonomy
- taxonomyTerm

outputs:
  home:
  - HTML
  - JSON
  page:
  - HTML
